### ISSUE TITLE
Menu class shouldn't be a class where you inherit from

### ISSUE THREAD

**Issue by TommyAlmeida** [heroslender/HeroAPI#1]
Not quite a issue, it's more like a code review.
https://github.com/heroslender/HeroAPI/blob/master/src/main/java/com/heroslender/Menu/Menu.java
By making this you are limiting the developer (since java only has 1 level of inheritance), the menu should be more flexible, instead of being a class that you inherit from.

"You're cutting the head of the developer"

Ass: AstroCoder

**Comment by heroslender** [comment]
Estavas-te a referir a isto?
![Screenshot](https://i.heroslender.com/04k9i.png)

**Comment by TommyAlmeida** [comment]
Yap

**Comment by heroslender** [comment]
Era suposto dar para fazer isso desde o inicio, mas por algum motivo não deixei os métodos/classes acessíveis. Obg por avisares xD
